In [1]:
!pip install gymnasium renderlab

!pip install opencv-python

!pip install pygame

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [68]:
import gymnasium as gym
import numpy as np
import random

In [69]:
desc=["SFFF", "FHHH", "FFFF", "HFHF", "FFGF"]

env = gym.make('FrozenLake-v1', desc=desc, map_name="5x5", is_slippery=False, render_mode="human")

observation, info = env.reset()

In [70]:
QTable

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
def epsilon_greedy(Q_values, epsilon):
    if np.random.rand() < epsilon:
        action = env.action_space.sample()  # Random action
    else:
        ind = 0
        maxIndices = []
        maxNum = -1
        for num in Q_table[state]:
            if num > maxNum:
                maxIndices = [ind]
                maxNum = num
            elif num == maxNum:
                maxIndices.append(ind)
            ind += 1
                
        maxInd = -1
        if len(maxIndices) >= 1:
            maxInd = maxIndices[random.randint(0, len(maxIndices) - 1)]
        
        print(maxInd)
        if maxInd== -1:
            maxInd = env.action_space.sample()
        action = maxInd  # Greedy action
    return action


In [72]:
Q_table = np.zeros((env.observation_space.n, env.action_space.n))

In [77]:
epsilon = 0.025  # Exploration rate
alpha = 0.1    # Learning rate
gamma = 0.9   # Discount factor
num_episodes = 1000

# Main loop
for episode in range(num_episodes):
    # Reset environment
    state = env.reset()[0]
    done = False
    # Run episode
    while not done:
        # Choose action based on epsilon-greedy policy
        action = epsilon_greedy(Q_table[state], epsilon)
        
        # Take action and observe next state and reward
        action_vals = env.step(action)
        next_state = action_vals[0]
        reward = action_vals[1]
        done = action_vals[2]
        
        if next_state == state:  # If the state didn't change, the action was invalid
            continue  # Skip updating Q-values

        
        # Update Q-value using Q-learning update rule
        Q_table[state][action] += alpha * (reward + gamma * np.max(Q_table[next_state]) - Q_table[state][action])
        
        # Update current state
        state = next_state
        if reward == 1:
            print(f"Reached gift on episode {episode}")


Reached gift on episode 86
Reached gift on episode 91
Reached gift on episode 110
Reached gift on episode 118
Reached gift on episode 119
Reached gift on episode 120
Reached gift on episode 121
Reached gift on episode 122
Reached gift on episode 123
Reached gift on episode 124
Reached gift on episode 125
Reached gift on episode 126
Reached gift on episode 127
Reached gift on episode 128
Reached gift on episode 129
Reached gift on episode 130
Reached gift on episode 131
Reached gift on episode 133


KeyboardInterrupt: 

In [75]:
Q_table

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ]])

In [30]:
env.reset()

(0, {'prob': 1})

In [46]:
Q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
env.step(0)

(4, 0.0, False, False, {'prob': 1.0})